# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Viewert < Formula
  desc "Viewert CLI — sync Vellums, manage Librams, and expose an MCP server for Claude"
  homepage "https://viewert.com"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/viewert/cli/releases/download/v0.1.3/viewert_0.1.3_darwin_amd64.tar.gz"
      sha256 "eb94e6377515f23f316ad77abed7d4b8c6f974b841272eed564ecd807a4da218"

      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/viewert/cli/releases/download/v0.1.3/viewert_0.1.3_darwin_arm64.tar.gz"
      sha256 "49653682443df838bfdcfc1496bcbfef0b1d267b8c6d25581f713b29afa45f1d"

      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/viewert/cli/releases/download/v0.1.3/viewert_0.1.3_linux_amd64.tar.gz"
      sha256 "6a60f709a56c803b63dc6a0d517cc11e50803e6743d4bdf6c80f5b9b1fd3bd6a"
      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/viewert/cli/releases/download/v0.1.3/viewert_0.1.3_linux_arm64.tar.gz"
      sha256 "1a833d01594a1afff7f77258341ad82ad0915a652fc1b2ed72a6fc45766e8865"
      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, log in to your Viewert account:
        v login

      To sync your Vellums to a local folder:
        v sync ~/my-vellums

      To use with Claude Desktop/Code, add to your MCP config:
        v mcp

      Both `v` and `viewert` are installed — they are identical binaries.
      Use whichever you prefer. All commands are available on both:
        v login        (or: viewert auth login)
        v ls           (or: viewert ls)
        v sync <dir>   (or: viewert sync <dir>)
    EOS
  end

  test do
    system "#{bin}/v", "version"
    system "#{bin}/viewert", "version"
  end
end
