# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Viewert < Formula
  desc "Viewert CLI — sync Vellums, manage Librams, and expose an MCP server for Claude"
  homepage "https://viewert.com"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/viewert/cli/releases/download/v0.1.1/viewert_0.1.1_darwin_amd64.tar.gz"
      sha256 "3872ced5cd8b1c17240e7f1dc5e69f60c8327e9992de67195dc537ee83bf94fe"

      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/viewert/cli/releases/download/v0.1.1/viewert_0.1.1_darwin_arm64.tar.gz"
      sha256 "de1c0d949c946eb14f89debab81c9b7e35b1697a46376b765859005d9cfacf5d"

      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/viewert/cli/releases/download/v0.1.1/viewert_0.1.1_linux_amd64.tar.gz"
      sha256 "2e3843ecf8599acb09124eced22eb3aa59ff5ba8daf8697a50abfc7b3cd6d5fc"
      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/viewert/cli/releases/download/v0.1.1/viewert_0.1.1_linux_arm64.tar.gz"
      sha256 "fffb256e10c9219b891bd9a0035709a99ef1199bc43dcf2945226cbd431476dd"
      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, log in to your Viewert account:
        v login

      To sync your Vellums to a local folder:
        v sync ~/my-vellums

      To use with Claude Desktop/Code, add to your MCP config:
        v mcp

      Both `v` and `viewert` are installed — they are identical binaries.
      Use whichever you prefer. All commands are available on both:
        v login        (or: viewert auth login)
        v ls           (or: viewert ls)
        v sync <dir>   (or: viewert sync <dir>)
    EOS
  end

  test do
    system "#{bin}/v", "version"
    system "#{bin}/viewert", "version"
  end
end
