# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Viewert < Formula
  desc "Viewert CLI — sync Vellums, manage Librams, and expose an MCP server for Claude"
  homepage "https://viewert.com"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/viewert/cli/releases/download/v0.1.2/viewert_0.1.2_darwin_amd64.tar.gz"
      sha256 "be55325619ecb4f12e3df2ee46cb73fc012c25c1d771dc4cce01f200530bd183"

      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/viewert/cli/releases/download/v0.1.2/viewert_0.1.2_darwin_arm64.tar.gz"
      sha256 "9eed4f4c4700c0ad23204cb03f7d3bc46679b3b8dc18cb6cc35f8b238614b9c3"

      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/viewert/cli/releases/download/v0.1.2/viewert_0.1.2_linux_amd64.tar.gz"
      sha256 "9fc31f8fb2bd30914b69778d439e3958a17b6cceabd1726faf61dd2cb3f64193"
      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/viewert/cli/releases/download/v0.1.2/viewert_0.1.2_linux_arm64.tar.gz"
      sha256 "7781ebc8bb66b73c256dee86fcf6ade2408e5d302515022a603614b82017b8fe"
      define_method(:install) do
        bin.install "viewert"
        bin.install "v"
      end
    end
  end

  def caveats
    <<~EOS
      To get started, log in to your Viewert account:
        v login

      To sync your Vellums to a local folder:
        v sync ~/my-vellums

      To use with Claude Desktop/Code, add to your MCP config:
        v mcp

      Both `v` and `viewert` are installed — they are identical binaries.
      Use whichever you prefer. All commands are available on both:
        v login        (or: viewert auth login)
        v ls           (or: viewert ls)
        v sync <dir>   (or: viewert sync <dir>)
    EOS
  end

  test do
    system "#{bin}/v", "version"
    system "#{bin}/viewert", "version"
  end
end
